"""Project indexer: dependency graph, summary generation, smart file selection.

Tiered context strategy:
  - Tiny   (<50 files):    Load all files directly
  - Small  (50-200 files):  Load all + project summary header
  - Medium (200-1000 files): Smart selection (top N by relevance) + summary
  - Large  (1000-10000):   Summary + changed files + dependency chain
  - Huge   (>10000 files): Tool-based exploration (agent navigates on-demand)
"""
from __future__ import annotations

import ast
import asyncio
import json
import logging
import os
import re
import subprocess
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from .constants import MAX_FILE_SIZE, SKIP_DIRS, SPECIAL_FILENAMES, STRUCTURE_EXTRACT_THRESHOLD, TEXT_EXTENSIONS

log = logging.getLogger("council.indexer")

# ── Auto-generated file markers (#18) ────────────────────────────

_GENERATED_MARKERS = (
    "// Code generated by",
    "# AUTOGENERATED",
    "// DO NOT EDIT",
    "@generated",
    "// This file is auto-generated",
    "# This file was automatically generated",
    "/* Auto-generated */",
    "// AUTO-GENERATED",
)

_GENERATED_SUFFIXES = frozenset({
    ".pb.go", ".d.ts", ".generated.ts", ".generated.js",
    ".min.js", ".min.css", ".bundle.js",
})

# ── Security-critical patterns (#14) ────────────────────────────

_SECURITY_FILE_PATTERNS = re.compile(
    r"(?:auth|password|token|encrypt|decrypt|jwt|oauth|session|"
    r"middleware[/\\]auth|guard|permission|credential|secret|"
    r"csrf|cors|sanitiz|hash|bcrypt|argon|scrypt|cert|ssl|tls)",
    re.IGNORECASE,
)


# ── Data models ──────────────────────────────────────────────────

@dataclass
class FileInfo:
    path: Path
    relative: str
    size: int
    language: str
    imports: list[str] = field(default_factory=list)
    exports: list[str] = field(default_factory=list)
    relevance_score: float = 0.0
    is_generated: bool = False


@dataclass
class ProjectIndex:
    root: Path
    total_files: int = 0
    total_size: int = 0
    files: list[FileInfo] = field(default_factory=list)
    dependency_graph: dict[str, list[str]] = field(default_factory=dict)
    entry_points: list[str] = field(default_factory=list)
    languages: dict[str, int] = field(default_factory=dict)
    framework: str = ""
    summary: str = ""
    tier: str = "tiny"

    @property
    def file_listing(self) -> str:
        """Compact file tree for agent context."""
        lines = [f"Project: {self.root.name} ({self.total_files} files, {self.total_size:,} bytes)"]
        lines.append(f"Languages: {', '.join(f'{k}({v})' for k, v in sorted(self.languages.items(), key=lambda x: -x[1]))}")
        if self.framework:
            lines.append(f"Framework: {self.framework}")
        if self.entry_points:
            lines.append(f"Entry points: {', '.join(self.entry_points[:10])}")
        lines.append("\nFile tree:")
        for fi in self.files[:200]:
            tag = " [GEN]" if fi.is_generated else ""
            lines.append(f"  {fi.relative} ({fi.size:,}b, {fi.language}){tag}")
        if self.total_files > 200:
            lines.append(f"  ... and {self.total_files - 200} more files")
        return "\n".join(lines)


# ── Language detection ───────────────────────────────────────────

_EXT_TO_LANG: dict[str, str] = {
    ".py": "python", ".js": "javascript", ".ts": "typescript",
    ".jsx": "react", ".tsx": "react-ts", ".json": "json",
    ".yaml": "yaml", ".yml": "yaml", ".toml": "toml",
    ".md": "markdown", ".html": "html", ".css": "css",
    ".scss": "scss", ".sql": "sql", ".sh": "shell",
    ".rs": "rust", ".go": "go", ".java": "java",
    ".c": "c", ".cpp": "cpp", ".h": "c-header",
    ".rb": "ruby", ".php": "php", ".swift": "swift",
    ".kt": "kotlin", ".dart": "dart", ".vue": "vue",
    ".svelte": "svelte", ".prisma": "prisma",
    ".graphql": "graphql", ".proto": "protobuf",
    ".tf": "terraform", ".hcl": "terraform",
    ".tfvars": "terraform", ".dockerfile": "docker",
    ".tpl": "template", ".conf": "config",
}


def detect_language(path: Path) -> str:
    name = path.name.lower()
    if name == "dockerfile" or name.startswith("dockerfile."):
        return "docker"
    if name == "makefile":
        return "make"
    return _EXT_TO_LANG.get(path.suffix.lower(), "other")


# ── Import extraction (#15 — fixed relative imports + TS) ────────

def extract_python_imports(content: str, file_relative: str = "") -> list[str]:
    """Extract imports from Python source using AST, including relative imports."""
    try:
        tree = ast.parse(content)
        imports = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.append(alias.name)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    if node.level > 0 and file_relative:
                        # Resolve relative import
                        parts = file_relative.replace("\\", "/").split("/")
                        # Go up `level` directories
                        base_parts = parts[:-1]  # remove filename
                        for _ in range(node.level - 1):
                            if base_parts:
                                base_parts.pop()
                        resolved = ".".join(base_parts + [node.module]) if base_parts else node.module
                        imports.append(resolved)
                    else:
                        imports.append(node.module)
                elif node.level > 0 and file_relative:
                    # `from . import X` — import from same package
                    parts = file_relative.replace("\\", "/").split("/")
                    base_parts = parts[:-1]
                    for _ in range(node.level - 1):
                        if base_parts:
                            base_parts.pop()
                    if base_parts:
                        imports.append(".".join(base_parts))
        return imports
    except SyntaxError:
        return re.findall(r"^(?:from|import)\s+([\w.]+)", content, re.MULTILINE)


def extract_js_imports(content: str) -> list[str]:
    """Extract imports from JS/TS source, including `import type`."""
    patterns = [
        r"import\s+(?:type\s+)?.*?from\s+['\"](.+?)['\"]",
        r"import\s*\(\s*['\"](.+?)['\"]",
        r"require\s*\(\s*['\"](.+?)['\"]",
        r"export\s+.*?from\s+['\"](.+?)['\"]",
    ]
    imports = []
    for p in patterns:
        imports.extend(re.findall(p, content))
    return imports


def extract_imports(content: str, language: str, file_relative: str = "") -> list[str]:
    """Extract imports based on language."""
    if language == "python":
        return extract_python_imports(content, file_relative)
    elif language in ("javascript", "typescript", "react", "react-ts"):
        return extract_js_imports(content)
    elif language == "go":
        return re.findall(r'"([\w./]+)"', content)
    elif language == "rust":
        return re.findall(r"use\s+([\w:]+)", content)
    elif language == "java":
        return re.findall(r"import\s+([\w.]+)", content)
    return []


# ── Entry point detection ────────────────────────────────────────

_ENTRY_POINT_NAMES = {
    "main.py", "app.py", "index.py", "server.py", "cli.py", "__main__.py",
    "index.js", "index.ts", "main.js", "main.ts", "app.js", "app.ts",
    "server.js", "server.ts", "main.go", "main.rs", "main.java",
    "manage.py", "wsgi.py", "asgi.py",
}

_ENTRY_POINT_PATTERNS = [
    re.compile(r'if\s+__name__\s*==\s*["\']__main__["\']'),
    re.compile(r"func\s+main\s*\("),
    re.compile(r"fn\s+main\s*\("),
    re.compile(r"public\s+static\s+void\s+main"),
]


def is_entry_point(path: Path, content: str) -> bool:
    if path.name.lower() in _ENTRY_POINT_NAMES:
        return True
    for p in _ENTRY_POINT_PATTERNS:
        if p.search(content):
            return True
    return False


# ── Config file detection (#17 — expanded coverage) ──────────────

_CONFIG_NAMES = {
    "package.json", "requirements.txt", "pyproject.toml", "setup.py",
    "setup.cfg", "cargo.toml", "go.mod", "go.sum", "pom.xml",
    "build.gradle", "gemfile", "composer.json", "mix.exs",
    "tsconfig.json", "webpack.config.js", "vite.config.ts",
    ".eslintrc", ".prettierrc", "docker-compose.yml", "docker-compose.yaml",
    "dockerfile", "makefile", ".env.example",
    # CI/CD configs
    ".github", ".gitlab-ci.yml", "jenkinsfile", ".circleci",
    "bitbucket-pipelines.yml", ".travis.yml",
    # Infrastructure
    "terraform.tfvars", "main.tf", "variables.tf",
    "chart.yaml", "values.yaml", "kustomization.yaml",
    "nginx.conf", "apache.conf", "caddy", "caddyfile",
}


def is_config_file(path: Path) -> bool:
    name = path.name.lower()
    if name in _CONFIG_NAMES:
        return True
    # CI/CD workflow files
    rel = str(path).replace("\\", "/").lower()
    if ".github/workflows/" in rel:
        return True
    if "helm/" in rel and name in ("chart.yaml", "values.yaml"):
        return True
    if "k8s/" in rel and name.endswith((".yaml", ".yml")):
        return True
    return False


# ── Framework detection (#9) ─────────────────────────────────────

def _detect_framework(idx: ProjectIndex) -> str:
    """Detect the project's framework from config files and entry points."""
    config_names = {fi.relative.split("/")[-1].lower() for fi in idx.files}
    all_imports: set[str] = set()
    for fi in idx.files:
        all_imports.update(fi.imports)

    frameworks = []

    # Python
    if "fastapi" in all_imports or "from fastapi" in str(all_imports):
        frameworks.append("FastAPI")
    if "django" in all_imports:
        frameworks.append("Django")
    if "flask" in all_imports:
        frameworks.append("Flask")

    # JavaScript/TypeScript
    if "next.config.js" in config_names or "next.config.ts" in config_names:
        frameworks.append("Next.js")
    if "nuxt.config.ts" in config_names or "nuxt.config.js" in config_names:
        frameworks.append("Nuxt")
    if "express" in all_imports:
        frameworks.append("Express")
    if "react" in all_imports:
        frameworks.append("React")
    if "vue" in all_imports:
        frameworks.append("Vue")
    if "svelte" in all_imports:
        frameworks.append("Svelte")

    # Others
    if "spring" in str(all_imports).lower():
        frameworks.append("Spring")
    if "rails" in str(all_imports).lower() or "gemfile" in config_names:
        frameworks.append("Rails")

    return ", ".join(frameworks) if frameworks else ""


# ── Generated file detection (#18) ──────────────────────────────

def _is_generated_file(path: Path, content_preview: str = "") -> bool:
    """Check if file is auto-generated via name patterns or content markers."""
    name = path.name.lower()
    # Check suffix patterns
    for suffix in _GENERATED_SUFFIXES:
        if name.endswith(suffix):
            return True
    # Check content markers (first 5 lines)
    if content_preview:
        lines = content_preview.split("\n")[:5]
        header = "\n".join(lines)
        for marker in _GENERATED_MARKERS:
            if marker.lower() in header.lower():
                return True
    return False


# ── Git integration ──────────────────────────────────────────────

def is_git_repo(root: Path) -> bool:
    """Check if path is inside a git repository."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=str(root), capture_output=True, text=True, timeout=5,
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return False


def get_git_changed_files(root: Path, base_ref: str = "HEAD~1") -> list[str]:
    """Get list of changed files from git diff."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", base_ref],
            cwd=str(root), capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            return [f.strip() for f in result.stdout.strip().split("\n") if f.strip()]
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass
    return []


def get_git_diff_content(root: Path, base_ref: str = "HEAD~1") -> str:
    """Get unified diff for changed files."""
    try:
        result = subprocess.run(
            ["git", "diff", "--unified=5", base_ref],
            cwd=str(root), capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return result.stdout[:500_000]
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass
    return ""


def _get_git_default_branch(root: Path) -> str | None:
    """Detect default branch (main/master)."""
    for branch in ("main", "master", "develop"):
        try:
            result = subprocess.run(
                ["git", "rev-parse", "--verify", branch],
                cwd=str(root), capture_output=True, text=True, timeout=5,
            )
            if result.returncode == 0:
                return branch
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            pass
    return None


# ── .gitignore parsing (#18) ────────────────────────────────────

def _load_gitignore_patterns(root: Path) -> list[str]:
    """Load .gitignore patterns for filtering."""
    gitignore = root / ".gitignore"
    if not gitignore.is_file():
        return []
    try:
        content = gitignore.read_text(encoding="utf-8", errors="replace")
        patterns = []
        for line in content.split("\n"):
            line = line.strip()
            if line and not line.startswith("#"):
                patterns.append(line)
        return patterns
    except Exception:
        return []


def _matches_gitignore(rel_path: str, patterns: list[str]) -> bool:
    """Simple gitignore matching (covers common patterns)."""
    from fnmatch import fnmatch
    for pat in patterns:
        # Directory patterns (ending with /)
        if pat.endswith("/"):
            dir_pat = pat[:-1]
            if any(part == dir_pat for part in rel_path.split("/")):
                return True
        # File/glob patterns
        if fnmatch(rel_path, pat) or fnmatch(rel_path.split("/")[-1], pat):
            return True
    return False


# ── Core indexer ─────────────────────────────────────────────────

def index_project(root: Path) -> ProjectIndex:
    """Build a project index: file listing, languages, imports, entry points."""
    idx = ProjectIndex(root=root)
    files: list[FileInfo] = []
    gitignore_patterns = _load_gitignore_patterns(root)

    for f in sorted(root.rglob("*")):
        if any(part in SKIP_DIRS for part in f.parts):
            continue
        if not f.is_file():
            continue

        # Extension filter
        if f.suffix.lower() not in TEXT_EXTENSIONS and f.name.lower() not in SPECIAL_FILENAMES:
            continue

        try:
            size = f.stat().st_size
        except OSError:
            continue
        if size > MAX_FILE_SIZE * 5:
            continue

        rel = str(f.relative_to(root)).replace("\\", "/")

        # .gitignore filter (#18)
        if gitignore_patterns and _matches_gitignore(rel, gitignore_patterns):
            continue

        lang = detect_language(f)
        fi = FileInfo(path=f, relative=rel, size=size, language=lang)
        files.append(fi)
        idx.total_size += size
        idx.languages[lang] = idx.languages.get(lang, 0) + 1

    idx.files = files
    idx.total_files = len(files)

    # Determine tier (#13 — updated thresholds for monorepos)
    if idx.total_files < 50:
        idx.tier = "tiny"
    elif idx.total_files < 200:
        idx.tier = "small"
    elif idx.total_files < 1000:
        idx.tier = "medium"
    elif idx.total_files < 10000:
        idx.tier = "large"
    else:
        idx.tier = "huge"

    # Extract imports + detect entry points + generated files
    if idx.tier != "huge":
        _enrich_files(idx)

    # Detect framework (#9)
    idx.framework = _detect_framework(idx)

    # Build dependency graph (#15 — with relative import support)
    _build_dependency_graph(idx)

    # Calculate relevance scores (#14 — with security boosting)
    _score_relevance(idx)

    # Sort by relevance
    idx.files.sort(key=lambda f: f.relevance_score, reverse=True)

    # Generate summary (#9 — with architecture overview)
    idx.summary = _generate_summary(idx)

    log.info(
        "Indexed %s: %d files, %s tier, framework=%s, top langs: %s",
        root.name, idx.total_files, idx.tier, idx.framework or "unknown",
        ", ".join(f"{k}({v})" for k, v in sorted(idx.languages.items(), key=lambda x: -x[1])[:5]),
    )
    return idx


def _enrich_files(idx: ProjectIndex) -> None:
    """Read file contents to extract imports, detect entry points and generated files."""
    for fi in idx.files:
        try:
            content = fi.path.read_text(encoding="utf-8", errors="replace")
            content_limited = content[:MAX_FILE_SIZE] if len(content) > MAX_FILE_SIZE else content

            # Generated file detection (#18)
            fi.is_generated = _is_generated_file(fi.path, content_limited[:500])
            if fi.is_generated:
                continue  # skip import extraction for generated files

            fi.imports = extract_imports(content_limited, fi.language, fi.relative)
            if is_entry_point(fi.path, content_limited):
                idx.entry_points.append(fi.relative)
        except Exception:
            pass


def _build_dependency_graph(idx: ProjectIndex) -> None:
    """Build dependency graph from imports (#15 — handles relative imports)."""
    file_modules: dict[str, str] = {}
    for fi in idx.files:
        rel = fi.relative
        if fi.language == "python":
            module = rel.replace("/", ".").replace("\\", ".")
            if module.endswith(".py"):
                module = module[:-3]
            if module.endswith(".__init__"):
                module = module[:-9]
            file_modules[module] = rel
        elif fi.language in ("javascript", "typescript", "react", "react-ts"):
            # Map JS/TS files by relative path without extension
            base = rel
            for ext in (".js", ".ts", ".jsx", ".tsx"):
                if base.endswith(ext):
                    base = base[:-len(ext)]
                    break
            file_modules[base] = rel
            # Also map with ./prefix stripped
            if "/" in base:
                file_modules["./" + base] = rel

    graph: dict[str, list[str]] = defaultdict(list)
    for fi in idx.files:
        for imp in fi.imports:
            # Try to resolve import to a local file — prefer longest (most specific) match
            best_mod = ""
            best_path = ""
            for mod, path in file_modules.items():
                if imp == mod or imp.startswith(mod + ".") or imp.startswith(mod + "/"):
                    if len(mod) > len(best_mod):
                        best_mod = mod
                        best_path = path
            matched = False
            if best_path and best_path != fi.relative:  # avoid self-loops
                graph[fi.relative].append(best_path)
                matched = True
            # For JS/TS relative imports (./foo, ../bar)
            if not matched and imp.startswith("."):
                # Resolve relative to importing file's directory
                parts = fi.relative.split("/")
                base_dir = "/".join(parts[:-1]) if len(parts) > 1 else ""
                if imp.startswith("./"):
                    resolved = (base_dir + "/" + imp[2:]).lstrip("/")
                elif imp.startswith("../"):
                    dir_parts = base_dir.split("/") if base_dir else []
                    imp_rest = imp
                    while imp_rest.startswith("../") and dir_parts:
                        dir_parts.pop()
                        imp_rest = imp_rest[3:]
                    resolved = ("/".join(dir_parts) + "/" + imp_rest).lstrip("/")
                else:
                    continue
                # Check if resolved path exists in modules
                if resolved in file_modules:
                    graph[fi.relative].append(file_modules[resolved])

    idx.dependency_graph = dict(graph)


def _score_relevance(idx: ProjectIndex) -> None:
    """Score file relevance (#14 — with security boosting)."""
    imported_by: dict[str, int] = defaultdict(int)
    for deps in idx.dependency_graph.values():
        for dep in deps:
            imported_by[dep] += 1

    for fi in idx.files:
        score = 0.0

        # Generated files get zero relevance
        if fi.is_generated:
            fi.relevance_score = 0.0
            continue

        # Entry points are highly relevant
        if fi.relative in idx.entry_points:
            score += 10.0

        # Config files are important
        if is_config_file(fi.path):
            score += 8.0

        # Security-critical files (#14)
        if _SECURITY_FILE_PATTERNS.search(fi.relative):
            score += 15.0
        else:
            # Also check first 500 chars of small files for security patterns
            try:
                if fi.size < 50_000:
                    content_preview = fi.path.read_text(encoding="utf-8", errors="replace")[:500]
                    if _SECURITY_FILE_PATTERNS.search(content_preview):
                        score += 12.0
            except Exception:
                pass

        # Files imported by many others (high centrality)
        score += imported_by.get(fi.relative, 0) * 2.0

        # Files that import many others
        score += len(fi.imports) * 0.5

        # Larger files tend to be more important (up to a point)
        score += min(fi.size / 10_000, 3.0)

        # Penalize test files slightly
        if any(p in fi.relative.lower() for p in ("test", "spec", "__test__", "_test")):
            score *= 0.5

        fi.relevance_score = round(score, 1)


def _generate_summary(idx: ProjectIndex) -> str:
    """Generate project summary with architecture overview (#9)."""
    lines = [
        f"# Project Summary: {idx.root.name}",
        f"- **Files:** {idx.total_files} ({idx.total_size:,} bytes)",
        f"- **Tier:** {idx.tier}",
        f"- **Languages:** {', '.join(f'{k} ({v})' for k, v in sorted(idx.languages.items(), key=lambda x: -x[1]))}",
    ]

    if idx.framework:
        lines.append(f"- **Framework:** {idx.framework}")
    if idx.entry_points:
        lines.append(f"- **Entry points:** {', '.join(idx.entry_points[:10])}")
    if idx.dependency_graph:
        lines.append(f"- **Dependency edges:** {sum(len(v) for v in idx.dependency_graph.values())}")

    # Generated file count
    gen_count = sum(1 for fi in idx.files if fi.is_generated)
    if gen_count:
        lines.append(f"- **Generated files:** {gen_count} (excluded from analysis)")

    # Architecture overview (#9)
    lines.append("\n## Architecture Overview")
    if idx.framework:
        lines.append(f"This appears to be a **{idx.framework}** project.")

    # Top modules by incoming edges (most depended upon)
    imported_by: dict[str, int] = defaultdict(int)
    for deps in idx.dependency_graph.values():
        for dep in deps:
            imported_by[dep] += 1
    if imported_by:
        top_modules = sorted(imported_by.items(), key=lambda x: -x[1])[:10]
        lines.append("\n### Core Modules (most imported)")
        for mod, count in top_modules:
            lines.append(f"- `{mod}` (imported by {count} files)")

    # Circular dependency warnings
    _circular = _detect_circular_deps(idx.dependency_graph)
    if _circular:
        lines.append(f"\n### Circular Dependencies ({len(_circular)} detected)")
        for cycle in _circular[:5]:
            lines.append(f"- {' -> '.join(cycle)}")

    # Key files by relevance
    lines.append("\n## Key Files (by relevance)")
    for fi in idx.files[:20]:
        tag = " [GEN]" if fi.is_generated else ""
        lines.append(f"- `{fi.relative}` (score={fi.relevance_score}, {fi.size:,}b, {fi.language}){tag}")

    # Dependency graph overview
    if idx.dependency_graph:
        lines.append("\n## Dependency Graph (top connections)")
        sorted_deps = sorted(idx.dependency_graph.items(), key=lambda x: len(x[1]), reverse=True)[:10]
        for src, deps in sorted_deps:
            lines.append(f"- `{src}` -> {', '.join(f'`{d}`' for d in deps[:5])}")

    return "\n".join(lines)


def _detect_circular_deps(graph: dict[str, list[str]]) -> list[list[str]]:
    """Detect circular dependencies (simple DFS)."""
    cycles: list[list[str]] = []
    visited: set[str] = set()
    path: list[str] = []
    on_stack: set[str] = set()

    def dfs(node: str) -> None:
        if len(cycles) >= 10:  # limit
            return
        if node in on_stack:
            # Found cycle
            start = path.index(node)
            cycles.append(path[start:] + [node])
            return
        if node in visited:
            return
        visited.add(node)
        on_stack.add(node)
        path.append(node)
        for dep in graph.get(node, []):
            dfs(dep)
        path.pop()
        on_stack.discard(node)

    for node in graph:
        if node not in visited:
            dfs(node)
    return cycles


# ── Context builders ─────────────────────────────────────────────

def build_context_for_tier(
    idx: ProjectIndex,
    max_chars: int = 5_000_000,
    git_base_ref: str | None = None,
) -> str:
    """Build appropriate context based on project tier.

    Args:
        idx: Project index
        max_chars: Maximum context size in characters
        git_base_ref: If set, include git diff and prioritize changed files
    """
    # Auto-detect git (#19)
    if git_base_ref is None and is_git_repo(idx.root):
        default_branch = _get_git_default_branch(idx.root)
        if default_branch:
            git_base_ref = default_branch

    if idx.tier == "huge":
        return (
            idx.summary
            + "\n\n## NOTE: Project too large for full context. "
            "Use the provided tools to search and read files on-demand.\n\n"
            + idx.file_listing
        )

    sections: list[str] = [idx.summary, ""]
    total_chars = len(sections[0])

    # Git diff mode: prioritize changed files (#19)
    changed_files: set[str] = set()
    if git_base_ref:
        changed = get_git_changed_files(idx.root, git_base_ref)
        changed_files = set(changed)
        diff = get_git_diff_content(idx.root, git_base_ref)
        if diff:
            diff_section = "## Git Diff\n```diff\n" + diff[:100_000] + "\n```\n"
            sections.append(diff_section)
            total_chars += len(diff_section)

    # Collect files to load based on tier
    files_to_load: list[FileInfo] = []

    if idx.tier in ("tiny", "small"):
        files_to_load = [fi for fi in idx.files if not fi.is_generated]
    elif idx.tier == "medium":
        top_n = 80  # increased from 50
        seen = set()
        for fi in idx.files:
            if fi.is_generated:
                continue
            if fi.relative in changed_files and fi.relative not in seen:
                files_to_load.append(fi)
                seen.add(fi.relative)
        for fi in idx.files:
            if fi.is_generated:
                continue
            if fi.relative not in seen:
                files_to_load.append(fi)
                seen.add(fi.relative)
            if len(files_to_load) >= top_n:
                break
    elif idx.tier == "large":
        top_n = 50
        seen = set()
        # Changed files + their dependencies
        for fi in idx.files:
            if fi.is_generated:
                continue
            if fi.relative in changed_files:
                files_to_load.append(fi)
                seen.add(fi.relative)
                for dep in idx.dependency_graph.get(fi.relative, []):
                    if dep not in seen:
                        dep_fi = next((f for f in idx.files if f.relative == dep), None)
                        if dep_fi and not dep_fi.is_generated:
                            files_to_load.append(dep_fi)
                            seen.add(dep)
        # Entry points + config
        for fi in idx.files:
            if fi.is_generated or fi.relative in seen:
                continue
            if fi.relative in idx.entry_points or is_config_file(fi.path):
                files_to_load.append(fi)
                seen.add(fi.relative)
        # Fill with top relevance
        for fi in idx.files:
            if fi.is_generated or fi.relative in seen:
                continue
            files_to_load.append(fi)
            seen.add(fi.relative)
            if len(files_to_load) >= top_n:
                break

    # Read and append file contents (#20 — priority-based smart truncation)
    from .file_reader import extract_code_structure

    loaded_count = 0
    for fi in files_to_load:
        if total_chars >= max_chars:
            sections.append(
                f"\n*[CONTEXT LIMIT: loaded {loaded_count} of {idx.total_files} files, "
                f"{total_chars:,} chars]*"
            )
            break
        try:
            content = fi.path.read_text(encoding="utf-8", errors="replace")

            # Priority-based file budget
            file_budget = MAX_FILE_SIZE
            if fi.relevance_score >= 8.0:
                file_budget = MAX_FILE_SIZE  # full budget for important files
            elif fi.relevance_score >= 4.0:
                file_budget = MAX_FILE_SIZE // 2
            else:
                file_budget = MAX_FILE_SIZE // 4

            marker = " [CHANGED]" if fi.relative in changed_files else ""
            truncation_note = ""

            if len(content) > file_budget:
                # For code files: extract structure (signatures + docstrings)
                if (fi.language in ("python", "javascript", "typescript", "react",
                                    "react-ts", "go", "rust", "java", "c", "cpp")
                        and len(content) > STRUCTURE_EXTRACT_THRESHOLD):
                    structure = extract_code_structure(content, fi.language, file_budget)
                    if len(structure) < len(content) * 0.8:
                        content = structure
                        truncation_note = " [STRUCTURE]"
                    else:
                        # Structure didn't compress enough — use head+tail
                        head_size = int(file_budget * 0.7)
                        tail_size = file_budget - head_size
                        content = (
                            content[:head_size]
                            + f"\n\n... [{len(content) - file_budget:,} chars omitted] ...\n\n"
                            + content[-tail_size:]
                        )
                else:
                    # Non-code or small overflow — head+tail
                    head_size = int(file_budget * 0.7)
                    tail_size = file_budget - head_size
                    content = (
                        content[:head_size]
                        + f"\n\n... [{len(content) - file_budget:,} chars omitted] ...\n\n"
                        + content[-tail_size:]
                    )

            section = f"### {fi.relative}{marker}{truncation_note}\n```\n{content}\n```\n"
            total_chars += len(section)
            sections.append(section)
            loaded_count += 1
        except Exception as e:
            sections.append(f"### {fi.relative}\n*Error: {e}*\n")

    # Files not loaded
    loaded_paths = {fi.relative for fi in files_to_load}
    not_loaded = [fi for fi in idx.files if fi.relative not in loaded_paths and not fi.is_generated]
    if not_loaded:
        sections.append(f"\n## Files Not Loaded ({len(not_loaded)} files)")
        for fi in not_loaded[:50]:
            sections.append(f"- `{fi.relative}` ({fi.size:,}b)")
        if len(not_loaded) > 50:
            sections.append(f"- ... and {len(not_loaded) - 50} more")

    return "\n".join(sections)
